name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # 2. Set up Node.js (for yarn)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.6.0' # 원하는 Node.js 버전으로 설정

      # 3. Install dependencies
      - name: Install dependencies
        run: yarn install

      # 4. Run build
      - name: Build project
        run: yarn build

      # 5. Deploy to the server
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # SSH private key를 GitHub Secrets에 추가해야 함
          SERVER_USER: ${{ secrets.SERVER_USER }} # 서버 사용자명
          SERVER_HOST: ${{ secrets.SERVER_HOST }} # 서버 주소
          SERVER_PATH: ${{ secrets.SERVER_PATH }} # 서버 내 배포할 경로
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -v -r dist/* $SERVER_USER@$SERVER_HOST:$SERVER_PATH
